import Link from "next/link";
import type { Score } from "@/lib/types";
import { MISTAKE_TAGS } from "@/lib/mistakes";
import { pickPrincipleForScore } from "@/lib/principles";
import { recommendLesson } from "@/lib/lessons";
import { primaryMistakeTag, primaryTermForTags, SEVERITY_CLASS, tagSeverity, termForTag } from "@/lib/learn";
import LessonCard from "./LessonCard";

type Props = { score: Score };

function scoreColor(pct: number): string {
  if (pct >= 0.8) return "text-good";
  if (pct >= 0.6) return "text-warn";
  return "text-bad";
}

export default function ReviewPanel({ score }: Props) {
  const pct = score.total / score.max;
  return (
    <div className="space-y-4">
      <div className="flex items-end justify-between">
        <h2 className="text-lg font-semibold">Decision review</h2>
        <div className="text-right">
          <div className={`text-3xl font-bold ${scoreColor(pct)}`}>
            {score.total}<span className="text-muted text-base">/{score.max}</span>
          </div>
          <div className="text-xs text-muted">decision quality</div>
        </div>
      </div>

      {/* v5.11.0 — each breakdown bar fills left→right with a stagger.
          Inline `--bar-pct` is the target width; the `--bar-delay` cascades
          ~70ms per row so the eye reads them as a sequence. */}
      <div className="space-y-1">
        {score.breakdown.map((b, i) => {
          const p = b.points / b.max;
          const pct = `${Math.max(0, p) * 100}%`;
          const delay = `${i * 70}ms`;
          return (
            <div key={b.id} className="flex items-center gap-3 text-sm">
              <div className="w-40 shrink-0 text-muted">{b.label}</div>
              <div className="flex-1 h-1.5 bg-panel2 rounded-full overflow-hidden">
                <div
                  className={`h-full animate-bar ${p >= 0.8 ? "bg-good" : p >= 0.5 ? "bg-warn" : "bg-bad"}`}
                  style={
                    {
                      ["--bar-pct" as string]: pct,
                      ["--bar-delay" as string]: delay,
                      width: pct,
                    } as React.CSSProperties
                  }
                />
              </div>
              <div className="w-12 text-right font-mono text-xs">
                {b.points}/{b.max}
              </div>
            </div>
          );
        })}
      </div>

      {score.tags.length > 0 && (
        <div>
          <div className="text-xs uppercase tracking-wide text-muted mb-2">Tags</div>
          <div className="flex flex-wrap gap-2">
            {score.tags.map((t) => {
              const info = MISTAKE_TAGS[t];
              const learn = termForTag(t);
              const sevClass = info.positive
                ? "border border-good/40 bg-good/10 text-good"
                : SEVERITY_CLASS[tagSeverity(t)];
              return (
                <span
                  key={t}
                  className={`inline-flex items-center gap-2 text-xs px-2 py-1 rounded-md ${sevClass}`}
                >
                  <span title={info.description}>{info.label}</span>
                  {learn && (
                    <Link
                      href={`/learn?term=${learn.id}`}
                      className="text-xs uppercase tracking-wide underline opacity-70 hover:opacity-100"
                    >
                      Learn this
                    </Link>
                  )}
                </span>
              );
            })}
          </div>
        </div>
      )}

      {score.strengths.length > 0 && (
        <Section title="What went right" color="good" items={score.strengths} />
      )}
      {score.weaknesses.length > 0 && (
        <Section title="What to improve" color="bad" items={score.weaknesses} />
      )}

      <LessonCard
        lesson={recommendLesson(score)}
        term={primaryTermForTags(score.tags)}
        primaryTag={primaryMistakeTag(score.tags)}
      />

      <WhyThisMatters score={score} />

      <div className="text-xs text-muted border-t border-line pt-3">
        Notes are generated by rule-based logic, not AI. They reflect decision quality at submission time — not
        whether the trade made money.
      </div>
    </div>
  );
}

function WhyThisMatters({ score }: { score: Score }) {
  const principle = pickPrincipleForScore(score);
  if (!principle) return null;
  return (
    <div className="rounded-md border border-accent/40 bg-accent/5 p-3">
      <div className="text-xs uppercase tracking-wide text-accent mb-1">Why this matters</div>
      <div className="text-sm font-semibold mb-1">{principle.title}</div>
      <p className="text-sm text-muted leading-snug">{principle.body}</p>
    </div>
  );
}

function Section({ title, color, items }: { title: string; color: "good" | "bad"; items: string[] }) {
  return (
    <div>
      <div className={`text-xs uppercase tracking-wide mb-2 ${color === "good" ? "text-good" : "text-bad"}`}>
        {title}
      </div>
      <ul className="space-y-1 text-sm">
        {items.map((s, i) => (
          <li key={i} className="flex gap-2">
            <span className={color === "good" ? "text-good" : "text-bad"}>•</span>
            <span>{s}</span>
          </li>
        ))}
      </ul>
    </div>
  );
}
