export type ChangelogEntry = {
  version: string;
  date: string; // ISO yyyy-mm-dd
  title: string;
  highlights: string[];
};

// Newest first. Used by the version-badge modal in app/layout.tsx.
export const CHANGELOG: ChangelogEntry[] = [
  {
    version: "5.12.2",
    date: "2026-06-07",
    title: "Trade-management reps across the library + more variety + polish",
    highlights: [
      "The 'manage the trade after entry' skill — move stop to break-even, take a partial, exit the runner — used to ship on only 3 of the 43 authored scenarios, so it almost never got practiced. It now appears on every scenario whose ideal trade actually runs in profit (3 → 18 authored, plus every favorable procedural one). Points are DERIVED from each scenario's ideal plan replayed through its real hidden candles: +1R → protect, +2R/near-target → partial, near target → exit, with prompts that quote the real price at that bar. Lose-before-+1R trades get no management — it only fires on the winners, where management changes the result.",
      "More procedural variety: LINK, AVAX, LTC, and DOT joined the synthetic symbol pool so generated charts feel less BTC/ETH/SOL-only.",
      "Loading polish: a shimmering skeleton (chart-shaped on Practice, hero-shaped on the Dashboard) replaces the bare 'Loading…' text on the surfaces you actually wait on. The score count-up no longer flashes the final number for a frame before it starts.",
    ],
  },
  {
    version: "5.11.1",
    date: "2026-06-06",
    title: "Purposeful motion + a shorter dashboard",
    highlights: [
      "A motion pass, all gated on prefers-reduced-motion: the score reveal counts up and pops in, the breakdown bars fill left→right in a stagger, the owl mascot bounces on a clear and gives a sympathetic shake on a rough one, and confetti bursts when an attempt clears (≥70%). Result panels and the home launcher cards cascade in; routes fade in; dropdowns and modals scale-fade open; every button dips slightly on press.",
      "The streak badge animates its digits and flashes a glow whenever the streak climbs; cleared scenario-path chips draw their own checkmark.",
      "The Dashboard is far shorter: the Jump-in launcher uses compact cards on a denser grid, and the redundant 'Your open sessions' section (already covered by the launcher) is gone.",
    ],
  },
  {
    version: "5.10.5",
    date: "2026-06-06",
    title: "Guided Scenario Path, a findable home launcher, and OpenAI support",
    highlights: [
      "New guided Scenario Path on Practice: an easy→hard ladder (Foundations / Building / Mastery) with progress and a 'Continue' that loads the next uncleared scenario (cleared = 70%+). The 'what actually happened' reveal was promoted out of the collapsed breakdown to always-visible — it's the best teaching moment.",
      "Home 'Jump in' launcher: a grouped grid (Trade / Learn / Track) surfacing the previously-buried Live Paper Trading, Portfolio, Candle School, and Drills — one glance from home. Live + Portfolio also joined the desktop nav. Every entry uses an original hand-drawn SVG symbol — no emojis.",
      "AI features now support OpenAI (ChatGPT) alongside Anthropic (Claude): a provider toggle in Settings, GPT-4o mini / GPT-4o models, and each provider's key kept independently.",
    ],
  },
  {
    version: "5.9.10",
    date: "2026-06-05",
    title: "Chris's Super Guppy, Candle School, and a leverage/liquidation rebuild",
    highlights: [
      "New 'Chris's Super Guppy' — a user-editable GMMA modelled on the TradingView indicator: a settings dialog for every fast/slow EMA, source, the optional EMA 200, and the 200-filter gate. The chart's Indicators row collapsed into a single 'Tools' dropdown.",
      "New Candle School (/learn/candles): an interactive identifier (shape a candle, see what it's called) plus a catalogue of the six patterns the chart flags.",
      "Fixed the chart tools on scenarios: the Guppy ribbons and EMA overlay were stuck gray / missing on short scenario charts because the long EMAs couldn't warm up — a best-effort EMA now renders and colors them correctly. The ribbon is one solid color, and the colorblind palette switched to blue/red.",
      "The tutorial's leverage step was rewritten in plainer language with a dedicated liquidation step (a shrinking leverage-ladder visual), the Practice walkthrough now draws entry/stop/TP on the chart as it narrates and is replayable, and thesis + invalidation grading got stricter (structure AND a specific price now required for full marks). Also: candle precision for low-priced coins, and background history auto-loading on Paper Trading.",
    ],
  },
  {
    version: "5.9.3",
    date: "2026-06-04",
    title: "Fix: Super Guppy colours now follow the obvious control",
    highlights: [
      "The Super Guppy ribbon's colour palette (Green/Red vs Blue/Orange) was controlled only by a buried toggle in Settings → Chart colors. After v6.0 added a prominent theme picker to the header, switching that — the obvious colour control — didn't touch the ribbon, so it appeared 'stuck in orange.'",
      "The trend-colour toggle now lives in the header theme picker too, under 'Chart trend colours.' Switching it repaints any open Super Guppy ribbon live, no reload — verified end to end (a bear ribbon flips from orange #ea580c to red #dc2626 the instant you switch). The Settings toggle still works for those who prefer it.",
      "The underlying repaint logic was never broken; this was purely a discoverability problem — the control that changes chart colours now sits where you look for colours.",
    ],
  },
  {
    version: "5.9.2",
    date: "2026-06-04",
    title: "v6.0 redesign, phase 3 — borderless editorial dashboard",
    highlights: [
      "The Dashboard now reads as one editorial column instead of a grid of bordered cards. The generic 'Dashboard' heading is gone — the personalised greeting hero (mascot + 'Where you left off.' in the display serif + your score sparkline) is the real masthead.",
      "The two entry surfaces — Portfolio Simulator and Live Paper Trading — became borderless rows under a hairline-divided 'Trading surfaces' section: display-serif titles, a hover tint instead of a box outline, live session stats inline in monospace, and a status dot when a session is active.",
      "The 'Today' progress (lesson / quiz / attempts) shed its border boxes too — now subtle tinted blocks where the fill and the completion ring carry the meaning, per the trainer's stated 'borderless hierarchy' principle (borders reserved for inputs, charts, and intentional callouts).",
      "Phase 3 of the 'Editorial Instrument' overhaul. Next: purposeful motion (rolling number tickers, route transitions, mascot reactions), then propagating the borderless language to every remaining surface for the v6.0.0 milestone.",
    ],
  },
  {
    version: "5.9.1",
    date: "2026-06-04",
    title: "v6.0 redesign, phase 2 — ⌘K command palette",
    highlights: [
      "Press ⌘K (Ctrl+K on Windows/Linux) anywhere to open a command palette — or '/' when you're not typing, or click the new search chip in the header. Jump to any page, switch theme, open the changelog, or deep-link straight to any of the 50+ scenarios and every Learn term without hunting through menus.",
      "Keyboard-first: ↑/↓ move the highlight, ↵ opens, esc closes. Empty query shows a calm short list of pages + actions; typing fuzzy-matches across scenarios, lessons, routes, and themes ranked by relevance. Selecting a scenario lands you in Practice on that exact chart; selecting a lesson opens it in Learn.",
      "Custom-built — no command-menu library — keeping the trainer's near-zero dependency surface and a look that matches the rest of the app rather than a stock widget. Lazy-loaded on first open, so it adds nothing to initial page weight (shared JS held at ~103 KB).",
      "Reuses the keyboard-navigation pattern from the v5.8 symbol picker, so arrow/Enter/Esc behave identically across the app.",
    ],
  },
  {
    version: "5.9.0",
    date: "2026-06-03",
    title: "v6.0 redesign, phase 1 — a real type system + five hand-tuned themes",
    highlights: [
      "First phase of the 'Editorial Instrument' overhaul. The trainer ditches the generic system-font stack for a three-role type system, self-hosted via next/font (no FOUC, no runtime Google call): Fraunces — a warm editorial serif — for headings; Hanken Grotesk (deliberately not Inter/Geist) for UI; IBM Plex Mono for every number. Headings now read like a typeset journal; prices and scores get true tabular figures.",
      "The theme system grew from a binary dark/light toggle to five named, hand-tuned themes: Leather (the warm dark default), Parchment (warm paper light), Terminal (amber/green phosphor on true black — an instrument homage), Slate (cool neutral dark), and High Contrast (a11y). The sun/moon toggle is now a proper theme picker with live color swatches and one-line character blurbs.",
      "Legacy 'dark'/'light' saved preferences migrate automatically to Leather/Parchment. The pre-paint bootstrap script was widened so theme selection still applies before first paint with zero flash.",
      "Craft layer: custom focus rings, a themed custom scrollbar, and a faint per-theme paper grain on the background for tactile depth. All motion (here and in later phases) is gated on prefers-reduced-motion.",
      "Foundation only — this phase changes the materials (type, color, texture), not yet the layouts. Phases ahead: a ⌘K command palette, a borderless editorial redesign of the dashboard and surfaces, and purposeful motion. Perf budget held: fonts are CSS, so the shared JS baseline is unchanged.",
    ],
  },
  {
    version: "5.8.5",
    date: "2026-06-02",
    title: "Real coin logos in the symbol picker + watchlist chips",
    highlights: [
      "The colored-initial avatars are now real coin logos — Bitcoin's orange ₿, Ethereum's blue diamond, Solana's gradient, 1inch's unicorn, Aave's ghost, etc. Logos load from a public icon CDN (jsDelivr's mirror of the cryptocurrency-icons set) keyed by lowercase ticker.",
      "Graceful fallback: the CDN is a static snapshot that doesn't cover the long tail of ~400 Coinbase pairs, so any coin without a logo (00 Token, Doublezero, Ancient8…) falls back to the same hue-hashed colored-initials avatar as before. You get logos where they exist and a clean colored chip everywhere else.",
      "Logos appear in both surfaces: the search picker rows and the watchlist tab chips. New shared components/paper-trading/CoinLogo.tsx owns the load-with-fallback logic (plain lazy <img>, no next/image remote-domain config needed).",
    ],
  },
  {
    version: "5.8.4",
    date: "2026-06-02",
    title: "Symbol search, TradingView-style — search by coin name, keyboard nav, colored avatars",
    highlights: [
      "Studied TradingView's symbol search directly and ported the two highest-value patterns. (1) Each result row now shows the FULL coin name beside the ticker — 'BTC Bitcoin', 'AAVE Aave', '1INCH 1inch' — so the list is scannable by name, not just ticker. Names come from Coinbase's /currencies endpoint, joined to the products by base-currency code (best-effort: the picker still works if /currencies hiccups).",
      "Search now matches the coin NAME too, not just the ticker. Typing 'bitcoin' finds BTC and BCH (Bitcoin Cash); typing 'avalanche' finds AVAX. Previously a name search returned nothing because the ticker is the only thing that was indexed.",
      "Keyboard-first navigation, like TV: the search field autofocuses, ↑/↓ move a highlight through the results (auto-scrolling into view), ↵ selects the highlighted row, Esc clears the query. A '↑↓ to navigate · ↵ to select' hint sits in the list header.",
      "Per-coin colored avatars — each ticker gets a stable hue hashed from its symbol, so rows have a TV-like visual anchor without depending on a logo CDN. A muted 'COINBASE · SPOT' venue badge sits in the header (TV shows the exchange per row because it aggregates many; we only have one, so it lives in the header once).",
      "lib/live-data.fetchCurrencyNames() is the new in-memory-cached fetch backing the names. Non-fatal on failure — returns an empty map rather than breaking the search.",
    ],
  },
  {
    version: "5.8.3",
    date: "2026-06-02",
    title: "Symbol picker redesign + 'Live Paper Trading' title case",
    highlights: [
      "The add-ticker search area is rebuilt search-first: a prominent search field with an inline magnifying-glass icon, accent focus ring, and a clear (✕) button. Popular pairs render as rounded pills that hide once you start typing so the panel stays focused on results.",
      "Catalog list redesigned — each row gets a ticker avatar (the base currency's first letters in a chip), the base symbol bold with a muted /USD, the full pair id beneath, and a check on the selected row. A header shows the live result count ('396 pairs' / '1 pair'). Loading state is a spinner, empty state quotes your query back.",
      "'Live paper trading' is now title-cased to 'Live Paper Trading' everywhere it appears as a heading — the page header, the dashboard card, and the session-ended summary — treating it as the proper product name.",
    ],
  },
  {
    version: "5.8.2",
    date: "2026-06-02",
    title: "Symbol-section redesign — watchlist chips + hero ticker, no more redundancy",
    highlights: [
      "The v5.8.1 symbol tabs ballooned to full-width on a single symbol — a giant near-empty card with a tiny sparkline floating in dead space, stacked directly above a PriceTicker showing the SAME price. Worse, the two disagreed: the tab showed percent over the entire loaded window (-10.86% across 463 bars) while the ticker showed a 24h-capped change (-0.93%). Two contradictory numbers for one symbol.",
      "Rebuilt as proper watchlist chips: compact fixed-width cards (164px) that never stretch, scroll horizontally when you've added several symbols, and show symbol / price / 24h change / sparkline / open-position PnL chip. The active chip gets an accent border; live ticks flash it briefly. This is the TradingView/Binance pattern — small watchlist entries, one big active price.",
      "The PriceTicker below is now the single hero: a 4xl mark price, 24h change, and a 24h high/low range bar with a marker showing where current price sits in the range. Both the chips and the hero share lib/price-stats so every percent on the page agrees.",
      "De-duplicated the bar count, which was showing in FOUR places (chip footer, ticker, load-older readout, status footer). Removed it from the hero ticker; the other three each have a distinct purpose.",
      "Page header subtitle now reflects the active symbol + a '+N more' count on multi-symbol sessions, instead of always showing symbols[0].",
    ],
  },
  {
    version: "5.8.1",
    date: "2026-06-02",
    title: "Symbol tabs polished — sparklines, big bold prices, live PnL chips, tick flash",
    highlights: [
      "Symbol tab strip rebuilt with proper trading-platform density. Big bold price as the dominant visual (font-mono, tabular-nums, ~24px), percent change with up/down arrow in directional color, mini SVG sparkline of the last 32 closes color-matched to the trend, granularity + bar count in a small muted footer.",
      "Live PnL chip replaces the v5.8.0 plain green dot. When you have open positions on a tab's symbol, the chip shows your aggregate R-multiple ('+1.2R' green, '-0.5R' red) — derived from positionMarkPnl, updates every render. No open positions = no chip, clean tab.",
      "Tick-flash animation. When the current candle's close ticks up or down, the tab briefly rings green or red (~500ms), then clears. Visual confirmation the polling loop is alive without watching the connection-status pill.",
      "Active tab gets a gradient bg + accent border + subtle shadow. Inactive tabs get a hover lift. The interaction feels deliberate rather than 'a row of buttons.'",
      "Add-pair tile redesigned: same height/shape as a real tab so the strip is uniform, but visually softer (dashed border, '+ Add pair' label). Picker confirmation row gets a tinted background so it stands out as 'in progress.'",
      "New lib/Sparkline.tsx is generic — takes any number[] + tone and draws a polyline with a soft fill area. Reused beyond the tabs if other surfaces ever want the same shape.",
    ],
  },
  {
    version: "5.8.0",
    date: "2026-06-02",
    title: "Mid-session symbol switching on /paper-trading — trade BTC + ETH + SOL in one session",
    highlights: [
      "New symbol-tabs strip above the chart. One tab per loaded symbol with live price + percent-from-session-open + granularity + bar count. An open-position dot lights up green on tabs where you have an active trade. Click any tab to switch — the chart, the ticker subscription, the in-progress bar, and the entry/stop/TP price lines all swap atomically. Active symbol persists per user.",
      "'+' button at the end of the tab strip opens an inline SymbolPicker. Pick any Coinbase USD pair (BTC, ETH, SOL, LINK, DOGE shortcuts or search the full ~200-pair catalog) and the new symbol gets its own initial-history fetch at the active symbol's current granularity. New tab becomes active automatically.",
      "Per-symbol drawing scopes already existed (the scope-id was 'live:SYMBOL:GRANULARITY' from v5.2.0); now mid-session symbol switching actually exercises them. Trendlines on BTC stay on BTC; horizontal levels on ETH stay on ETH.",
      "Entry/stop/TP/liquidation price lines on the chart filter to the active symbol — an ETH-USD trade no longer paints a garbage horizontal on the BTC-USD chart.",
      "Position list still shows positions across all symbols (intentional — open-position awareness shouldn't depend on which tab you're looking at). Each row already shows the symbol name in the v4.1 PositionList shape, so reading multi-symbol positions is legible.",
      "Architecture: PortfolioSession.symbols[] already supported multi-symbol from the v4.1 portfolio simulator. lib/portfolio.addLiveSymbol is the new helper that grows a live session by one symbol mid-stream. Live-polling iterates session.symbols already, so the new symbol's candles start flowing on the next tick with zero extra wiring.",
    ],
  },
  {
    version: "5.7.0",
    date: "2026-06-02",
    title: "Multi-symbol on /paper-trading — pick from ~200 Coinbase USD pairs",
    highlights: [
      "The single-symbol limitation is gone. /paper-trading's start screen now ships a symbol picker: a strip of popular shortcuts (BTC / ETH / SOL / LINK / DOGE) plus a search box that filters the full Coinbase USD product catalog (~200 pairs). Pick AVAX, MATIC, ATOM, anything Coinbase quotes against USD.",
      "Symbol persists per user via lib/storage.{get,set}LastPaperSymbol. Returning visitors land on the picker pre-selected to their last choice — no re-typing.",
      "Single-symbol-per-session still the rule (mid-session symbol switching is a deeper refactor). To trade a different symbol: End session → Start new session → pick the new symbol. Open positions are session-scoped, so this is intentional, not a bug.",
      "lib/live-data.fetchProducts() pulls Coinbase's /products endpoint once per page mount and caches in-memory. Filters to online + tradeable + USD-quoted spot pairs — strips the EUR / GBP / USDT / USDC quote-currency clones, the delisted pairs, and the post-only ones that would silently reject orders.",
      "Three new Vitest cases pinning the products fetch + filter contract. Bug-fix: the start-screen 'BTC-USD only at launch' subtitle is gone; replaced with copy that's accurate to the new picker.",
    ],
  },
  {
    version: "5.6.6",
    date: "2026-06-02",
    title: "Fix: Super Guppy palette stuck after a same-tab Settings change",
    highlights: [
      "Switching the chart color mode in Settings (colorblind ↔ standard) didn't take effect on charts already open in another route until the window lost and regained focus. Native 'storage' events only fire for OTHER tabs in the same origin — same-tab writes were silent.",
      "Fix: setColorMode now dispatches a 'trainer:color-mode-change' custom window event after writing to localStorage. Chart.tsx listens for it alongside the existing storage + focus signals, so navigating Settings → /paper-trading → see the new palette immediately.",
    ],
  },
  {
    version: "5.6.5",
    date: "2026-06-02",
    title: "/paper-trading polish pass — price ticker, hide drawings, risk presets, status footer",
    highlights: [
      "New TradingView-style price ticker above the chart. Big bold mark price + 24h change in dollars and percent, color-coded by direction. Pulses green or red on every closed-candle tick — connection-status feedback you can read across the room. Adapts to whatever lookback the loaded history allows ('vs 8h ago' when you haven't loaded a full 24h yet).",
      "Eye-icon 'Hide drawings' toggle in the Drawings bar. Hides every persisted trendline and horizontal line on the chart without deleting them — for those moments when you want a clean read of structure. Toggle back to restore. Drawings stay in localStorage either way.",
      "Risk-percent preset chips in the Open Position form. 0.5% / 1% / 2% / 5% buttons under the Risk field. Current chip highlights based on the typed value so the relationship between input and preset is visible. Hover tooltips explain the trade-offs at each level ('Conservative — the trainer's default range' through 'Very aggressive — five losses in a row is a -25% drawdown').",
      "Subtle status footer at the bottom of /paper-trading: build version, current symbol + granularity, bar count, browser timezone, last successful tick freshness ('12s ago'). Read-only — the 'this is a real tool' cue without taking real screen real estate.",
      "Design pass took notes from TradingView (left-rail drawing tools, prominent ticker, eye toggle, status footer), Binance/Coinbase Pro (risk presets, in-form liquidation), and Apex (hotkey legend, chart-trading affordances). What we shipped is what works at our 'beginner crypto trainer' altitude without bolting on full-broker complexity.",
    ],
  },
  {
    version: "5.6.4",
    date: "2026-06-02",
    title: "Crash fix: preview-line crosshair handler no longer recurses into itself",
    highlights: [
      "The trendline / measure preview line introduced in v5.6.0 could trigger a 'Maximum call stack size exceeded' RangeError on the live chart. Root cause: setData() on a line series whose data sits at the cursor causes lightweight-charts to fire another crosshair-move event (the data at the cursor changed), which re-enters the same handler, calls setData again, and overflows the stack.",
      "Added a re-entry guard ref. The handler skips the update if it's already mid-setData. The user-visible effect: zero. The preview line still updates on every cursor move; just not on the recursive event lightweight-charts fires in response to its own setData call.",
    ],
  },
  {
    version: "5.6.3",
    date: "2026-06-02",
    title: "⏪ Load all — stream the full chart back to Coinbase's listing date",
    highlights: [
      "Joining the per-page '← Load 280 older' button: a new '⏪ Load all' button that streams every available history page until Coinbase returns empty. 200ms politeness delay between requests so we don't trip Coinbase's public-API rate limit even when paginating thousands of pages.",
      "Honest about cost on fine granularities. Clicking 'Load all' on 5m, 15m, or 1m fires a confirm dialog warning the operation will take 5+ minutes (15m) / 20+ minutes (5m) / hours (1m). On 1d / 6h / 1h it's fast enough to skip the warning — 1d back to 2015 streams in ~4 seconds.",
      "Stop button replaces 'Load all' while a stream is in flight. Aborting halts the loop after the current page completes (not mid-fetch — partial pages would corrupt the candle array). Resume from where you stopped with another 'Load all' or 'Load 280 older' click.",
      "Bar count read-out now shows 'streaming · 3,500 bars loaded' during a stream so progress is visible in real time. The chart re-renders on every successful page — you can see history unfold one batch at a time.",
    ],
  },
  {
    version: "5.6.2",
    date: "2026-06-02",
    title: "Load older — paginate /paper-trading history back to Coinbase's listing date",
    highlights: [
      "New '← Load 280 older bars' button above the live chart. Each click fetches the next page of historical candles via a paginated Coinbase request. Open positions stay open; their openedAtIdx pointers re-anchor to the new index space so SL/TP scanning still works correctly. Bar-count read-out next to the button shows your current depth.",
      "Goes back to Coinbase's earliest data for the pair — not the coin's actual creation date (Coinbase didn't list BTC-USD until ~2015 via GDAX). On 1d granularity that's ~3,650 bars = 13 clicks to ~9 years of history; on 1h granularity 200+ clicks for the same depth; on 1m the math just doesn't pencil out (~5M bars). The button doesn't gate by granularity — the rate limit is the natural ceiling.",
      "Latches '← End of Coinbase data' when the API returns an empty page so the button can't keep hitting a dead endpoint. Reset on every timeframe switch since a coarser interval may reach further back than the previous one allowed.",
      "lib/portfolio.prependLiveCandles handles the index-shifting math for existing positions — every position.openedAtIdx (and exitIdx for closed ones) gets incremented by the prepend count so the candle-array → position-pointer relationship stays consistent. Pure helper, no side effects.",
    ],
  },
  {
    version: "5.6.1",
    date: "2026-06-02",
    title: "More history on /paper-trading — 150 → 280 candles per fetch",
    highlights: [
      "Initial session fetch and timeframe-switcher fetch both pulled 150 candles. On 1m granularity that was only 2.5 hours of chart — not enough history to read structure. Bumped to 280 (safe margin under Coinbase's ~300 cap). New windows: ~4.7h on 1m, ~23h on 5m, ~70h on 15m, ~11.7d on 1h, ~70d on 6h, ~9 months on 1d.",
    ],
  },
  {
    version: "5.6.0",
    date: "2026-06-02",
    title: "Chart-tools polish + leverage proximity warning on /paper-trading",
    highlights: [
      "Trendline and Measure tools now show a live preview line during the draw. Click point 1, move the cursor, and a dashed amber (trendline) or cyan (measure) line follows the cursor — you see exactly where it'll land before clicking point 2. Esc clears the preview. Mode-deactivate clears it too.",
      "Open leveraged positions get a dashed red 'liq <N×' price line on the chart, alongside the existing entry/stop/TP lines. You can see at-a-glance how close current price is to triggering a forced close. Same treatment on /portfolio.",
      "New liquidation-proximity banner above the chart. When an open leveraged position is within 20% of its liquidation level (entry-to-liq distance remaining), an orange 'Close to liquidation' banner names the position, shows mark vs liq, and points out that this is the moment to re-evaluate the thesis. Under 5% the banner turns red 'Liquidation imminent.' Doesn't auto-close — that would defeat the lesson; just makes the risk visible.",
      "Session summaries (both /paper-trading and /portfolio) now count the 'closed_liq' status as its own outcome bucket — leveraged blowups no longer silently vanish from the trade count and breakdown. Liq count badges in red when present.",
      "Bug fixes: endSession's mark-to-close path now subtracts accrued funding cost on still-open leveraged positions (previously the PnL was overstated by the funding drag). OpenPositionForm imports OpenPositionParams directly from lib/portfolio instead of redeclaring it inline — prevents the two from drifting on future field additions.",
    ],
  },
  {
    version: "5.5.0",
    date: "2026-06-02",
    title: "Curriculum backfill — three new modules graduate to full Teach → Practice → Test",
    highlights: [
      "Three modules that have been term-cards-only since v3.2 now ship with full course steps: Leverage and liquidation (3 steps using real-data leverage_trap scenarios), Discipline and traps (2 steps focused on the WAIT decision + trade management on range_chop charts), Planning a trade (3 steps walking thesis → invalidation → target realism through clean-retest / failed-breakout / trend-continuation scenarios).",
      "The Leverage module pairs intentionally with v5.3.0: now that /paper-trading actually has leverage and liquidation, the curriculum can teach the concepts and then send the learner to apply them on real Coinbase prices. The Practice scenarios use the same lt-btc-* real-data charts that scored as 'leverage_trap' setups going back to 2020.",
      "The Discipline module pairs with v5.4.0's losing_streak lesson banner — the banner's 'Learn more →' link now lands on a full course, not a term card.",
      "Module counts: 5 of 9 modules now have full steps (Foundations, Risk basics, Chart tools momentum, Chart tools volume, Leverage, Discipline, Planning — actually 7 of 9). Remaining 2 (Portfolio thinking, Crypto signals) need a CurriculumStep variant that points at a portfolio challenge or a watchlist instead of a single-scenario journal entry — deferred to a future release.",
      "No new code surfaces; CurriculumStep / CoursePlayer already handled this case. The only edit is lib/curriculum.ts — six new steps + their summary updates.",
    ],
  },
  {
    version: "5.4.0",
    date: "2026-06-02",
    title: "Lessons along the paper-trading path — closes the 'siloed sandbox' gap",
    highlights: [
      "/paper-trading no longer just displays — it teaches. New contextual lesson banner fires at the moments where a beginner benefits most: first trade overall, first leveraged trade, first 10×+ leverage, first liquidation, first short, three consecutive losses. One banner at a time, dismissed with 'Got it', persists per-user.",
      "Priority order: liquidation > losing streak > high-leverage > leverage > short > first-trade. A user who hits a liquidation on their first leveraged trade sees the liquidation lesson, not the 'welcome to perps' card it would otherwise queue — the higher-impact moment wins.",
      "Each banner carries a plain-English body (mirrors the matching Learn term's voice register) plus a 'Learn more →' deep link to the full term, so the in-context card is the hook and the term is the depth.",
      "Tone-coded styling: info (blue, FYI cards), warn (orange, 'you're taking on real risk now'), alert (red, outcome-driven moments like a liquidation). Matches the rest of the trainer's accent system.",
      "lib/paper-trading-lessons.ts owns the pure decision logic — given a session and a set of dismissed ids, return the highest-priority eligible lesson or null. 9 new Vitest cases pin the priority order, the loss-streak detector, and the seen-set respect. Settings → Data management can clear the seen set if you want to re-see the lessons after a long break.",
      "This is the structural fix for the 'paper trading siloed from learning' critique. v5.5+ will start backfilling the curriculum modules that are still term-cards only.",
    ],
  },
  {
    version: "5.3.0",
    date: "2026-06-02",
    title: "Perpetual futures with leverage on /paper-trading and /portfolio",
    highlights: [
      "The order form gains a 1× / 2× / 5× / 10× / 25× leverage tier picker. 1× is spot (the existing behaviour); anything higher is a perpetual-futures-style position with a calculated liquidation level and accrued funding cost. Higher tiers paint warning / bad colors so the cost of the choice reads on hover before submit.",
      "Liquidation math: standard formula (entry × (1 ± (1 - maintenance) / leverage)) with maintenance margin pegged at 0.5%. The form shows the live liq price and the percent distance from current price; the position list shows it as a 'Liq @' line under each leveraged position. If price wicks through it on any candle during advanceTo, the position closes_liq with a full-margin loss (pnlPercent = -riskPercent × leverage, plus any funding accrued).",
      "Funding: 0.01% per 8h baseline (typical Binance/Bybit perp rate), prorated linearly per candle interval, applied to notional position size. Longs pay; shorts receive. Accumulated cost is stamped onto the position so the mark-to-market and the realized P&L both reflect the drag. Spot positions skip funding entirely.",
      "Stop-vs-liq trap is caught at submit time: if your stop sits past your own liquidation, openPosition throws with a 'use lower leverage or tighter stop' message. The form previews this with a red warning chip before submit — exactly the lesson the existing 'leverage_trap' Learn term teaches.",
      "Position list grows a leverage badge next to the symbol (color-coded by tier — yellow for 2-5×, red for 10×+), a Liq line, and a Funding line. New 'Liquidated' status replaces the previous 'Closed' on liquidation outcomes so the journal can distinguish the cause.",
      "New lib/leverage.ts owns the pure math (liquidationPrice, fundingCostForCandle, wasLiquidated) with 17 new Vitest cases pinning long/short symmetry, the formula derivation, funding scaling with leverage and interval, and the liquidation-check intra-bar semantics. Portfolio mechanics tests gain four leverage-specific cases. 250 tests total.",
    ],
  },
  {
    version: "5.2.3",
    date: "2026-06-02",
    title: "Horizontal line drawing — one-click support/resistance levels",
    highlights: [
      "New '➖ Horizontal' button in the Drawings bar. Click once anywhere on the chart and a horizontal price line drops at that price, spanning the full chart with the price label on the axis. Persists per-scope alongside trendlines.",
      "Single-click handshake (vs Trendline's two-click) — horizontal levels are common enough that the extra click for a 'second point' would feel wrong. Click → line → next chart click drops another. Esc cancels arm.",
      "Renders via lightweight-charts' createPriceLine so the line auto-spans across the chart as new candles arrive (important on /paper-trading where the chart grows on every tick). Trendlines still use two-point line series since they're inherently sloped.",
      "Drawing type is now a discriminated union (TrendlineDrawing | HorizontalDrawing). Future drawing modes (ray, channel, Fib retrace) slot in by adding a union arm + a renderer branch — same pattern as the indicator-meta registry.",
      "Three new Vitest cases pinning the horizontal round-trip, coexistence with trendlines in the same scope, and id-targeted removal that doesn't disturb the other kind. 233 tests total.",
    ],
  },
  {
    version: "5.2.2",
    date: "2026-06-02",
    title: "Candle patterns — auto-detected markers for six common single + two-bar shapes",
    highlights: [
      "New 'Patterns' toggle on the Indicators bar. When on, the trainer scans the chart and surfaces markers for six classic candle patterns: Doji (indecision), Hammer (bullish reversal), Shooting Star (bearish reversal), Bullish Engulfing, Bearish Engulfing, and Inside Bar (consolidation).",
      "Markers are conservative by design — body-to-range and wick-to-body thresholds are tuned so only the cleanest examples flag. Better to under-mark than train the user to see patterns where there aren't any. Each marker carries the pattern name as text so a hover reveals which kind it is.",
      "Marker geometry encodes direction: bullish reversals (Hammer, Bullish Engulfing) show as arrows below the bar pointing up; bearish reversals show as arrows above pointing down; neutral patterns (Doji, Inside Bar) show as small shapes above the bar.",
      "New Learn term: 'Candle patterns' in the Chart tools category. Walks through why pattern recognition is a foundational skill, when to trust a pattern (in context with structure), when to ignore one (in chop, alone). Wired into the chart-tools scoring category so a thesis that names 'hammer' or 'engulfing' on a scenario where one's clearly visible earns the bonus.",
      "Pure detection logic lives in lib/candle-patterns.ts with 14 new Vitest cases pinning each threshold. Future patterns (Three White Soldiers, Tweezer Top/Bottom, Marubozu) can be added by appending one detector function and one config row — same registry pattern the rest of the chart-tools work uses.",
    ],
  },
  {
    version: "5.2.1",
    date: "2026-06-02",
    title: "Measure tool — click two chart points, get the price + time + R math instantly",
    highlights: [
      "New '📐 Measure' button next to the Trendline tool on every chart with a Drawings bar. Click two points and an inline overlay pops up showing: price delta in dollars, percent change, number of candles between, time delta ('3d 4h', '2h 30m'), and the implied R-multiple if you treated those two prices as entry → target.",
      "The overlay is color-coded by direction: up moves get the active palette's bull color (blue in colorblind mode, green in standard); down moves get the bear color. Same trend-color system the Super Guppy uses, so the reading stays accessible regardless of color-vision setting.",
      "Ephemeral by design — the measure result is a temporary overlay, not a persisted drawing. Click the ✕, hit Escape, or start a new measurement to dismiss. Useful for 'how big was that move?' questions without cluttering the chart with permanent annotations.",
      "Pure helpers in lib/measure.ts: computeMeasure (signed deltas, percent against the earlier point, candle count via binary search) and formatTimeDelta (compact human strings like '1d 4h' that fit the overlay box). 17 new Vitest cases pin the formatting + the direction classifier + the symmetric-input invariant (click order doesn't change the measurement).",
    ],
  },
  {
    version: "5.2.0",
    date: "2026-06-02",
    title: "Two more chart tools + the first drawing tool — trendlines",
    highlights: [
      "Keltner Channels toggle. EMA(20) midline with ATR(10)-based ±2 bands in a pink palette so it reads as distinct from Bollinger when both are on. Width tracks volatility differently than BB — Keltner widens with trend; BB narrows in a squeeze and expands on the breakout. Reading both together is more informative than either alone.",
      "Pivot Points toggle. Five horizontal price levels (central pivot, R1/R2, S1/S2) computed from the first ~25% of the visible candles (the 'reference window'). Drawn as axis-labelled price lines so you can see exact prices, not just colored lines. R levels lean red, S levels lean green so the labels read directionally even without the R/S text.",
      "First user-drawing tool: Trendlines. A new 'Drawings' bar next to Indicators on /practice and /paper-trading. Click '📏 Trendline', click two points on the chart, line is drawn. Persists per-scope in localStorage (scenario id on Practice; symbol + granularity on Paper Trading). Escape cancels mid-draw; 'Clear (N)' wipes all lines on the active chart.",
      "Same registry plumbing every chart-tool ship gets: hover labels identify each Keltner/Pivot line by name + meaning, the always-visible legend lists their current values, ChartToolsHelp gains two new cards, INDICATOR_KEYWORDS picks up 'keltner', 'pivot', 'r1', 's1' etc. so the chart_tools scoring category rewards a thesis that names them.",
      "New pure math: lib/indicators.atr(period) using Wilder's smoothing and lib/indicators.keltnerChannels(...). lib/pivot-points.ts owns the floor-trader formula + a default-window heuristic. lib/drawings.ts owns the persistence shape and discriminated-union types so future drawing modes (horizontal line, ray, channel) join cleanly. 20+ new Vitest cases across the four modules pin the math, the storage contract, and the registry shape.",
    ],
  },
  {
    version: "5.1.2",
    date: "2026-06-02",
    title: "Super Guppy ribbon visibility fix — wider gradient, opacity, gray neutral",
    highlights: [
      "Ribbon now reads as a band, not a single line. The previous v5.1.1 palette endpoints (blue-500 → cyan-500, green-500 → green-600, etc.) were too close in hue, so when the 12 EMAs in a cluster compressed into a thin price range they blended into one colored stripe. Each cluster now spans a clear luminance gradient (pale → vivid → deep), and ribbon lines render at 0.75 alpha so overlapping neighbors compound visibly. Line width bumped from 1 to 2 so a single line is recognisable as part of a band.",
      "Neutral palette is gray in both color modes (was amber/yellow in Standard). The old Standard-mode 'MIXED' state looked orange — easy to confuse with colorblind mode's bear-orange after a palette switch. Gray reads unambiguously as 'no clear trend' in either mode and removes the visual collision.",
      "Bull / bear representative colors bumped one notch darker for higher contrast against the dark panel background. Colorblind bull: blue-500 → blue-600. Standard bull: green-500 → green-600. Same one-step shift for bear.",
      "Three new tests pinning the opacity-encoded path in lib/color-mode.ts (rgba output when opacity < 1, rgb fallback when omitted or = 1) plus a regression test on gray-neutral parity across both modes.",
    ],
  },
  {
    version: "5.1.1",
    date: "2026-06-02",
    title: "Super Guppy ribbon — 24-EMA trend visualizer, colorblind-friendly by default",
    highlights: [
      "New 'Super Guppy' toggle on every chart that takes overlays. Renders 24 EMAs in two color-coded ribbons (short cluster 3–25 every 2, long cluster 28–61 every 3). When the entire short ribbon sits above the entire long ribbon, the trend is up; below, down; interleaved, mixed. The color flip — the 'Super' part — gives you the trend state at a glance instead of by counting lines.",
      "Colorblind-friendly by default. The standard green/red palette isn't readable for users with red/green colorblindness, so the trainer ships with blue (uptrend) / orange (downtrend) / gray (mixed) by default. New Settings → Chart colors section to switch to the classic green/red palette for users who prefer it; the picker shows a live preview of both palettes so the difference is obvious before you pick.",
      "Single legend row + state chip. Listing 24 individual EMAs in the chart legend would crush every other indicator off the screen, so the ribbon collapses to a single row that shows the live trend state ('BULL' / 'BEAR' / 'MIXED') in the active palette's color. Hover near any ribbon line and the tooltip headline names the state, the meaning sentence, and links to the full Learn term — same hover treatment v5.1.0 added for the other indicators.",
      "New Learn term super_guppy with the standard template (simple definition, why it matters, worked example, common mistake, scoring note) plus a two-question quiz. ChartToolsHelp gains a sixth card with a worked example. The Settings → Default chart overlays panel includes Super Guppy too so you can default it on if you want it everywhere.",
      "Pure math lives in lib/indicators-guppy.ts (24 EMAs reusing the existing ema() helper, strict-separation trend state classifier). Palette resolution + color interpolation live in lib/color-mode.ts. Both modules ship with Vitest coverage pinning the period set, warmup behavior, strict-separation classifier (bull / bear / neutral), and the palette resolver — refactors can't silently break the ribbon's coloring or trigger conditions.",
    ],
  },
  {
    version: "5.1.0",
    date: "2026-06-01",
    title: "Chart-tool hover labels — point at any line and the trainer tells you what it is",
    highlights: [
      "Point at any EMA, Bollinger Band, VWAP, RSI line, or MACD series on the chart and a floating tooltip names it, shows its current value, gives a one-sentence meaning, and offers a 'Learn more →' link to the full term. Solves the 'which yellow line is EMA 20 vs EMA 50' problem in place, without leaving the chart.",
      "Always-visible legend in the top-right corner of every chart that draws overlays — main pane and RSI/MACD sub-panels. One row per visible line with a color swatch, name, and (when the crosshair is over the chart) the current value. Each row is clickable and deep-links to the Learn term so a curious user is one click from the lesson.",
      "New central registry lib/indicator-meta.ts: one entry per drawn series (ema20/50/200, bb_upper/middle/lower, vwap, rsi, macd_line/signal/histogram) with name, color, one-line meaning, Learn slug, and numeric formatter. Colors moved here so the legend swatch, the tooltip dot, and the drawn line can never drift apart.",
      "Closest-line proximity: when the cursor is within ~14px of a specific line, the tooltip foregrounds that line's card (color dot + name + value + meaning + Learn link). When it's not, the tooltip falls back to a compact list of every visible overlay's current value, so the readings are always one glance away.",
      "All four chart surfaces — /practice, /paper-trading, /portfolio, and the Context-first drill — inherit the hover labels and legend automatically since they share the same Chart and IndicatorSubChart components. Future overlays (trendlines, Fib, channels — when they land) join the system by adding one row to the meta registry.",
    ],
  },
  {
    version: "5.0.0",
    date: "2026-05-31",
    title: "Live paper trading — real Coinbase prices, paper money",
    highlights: [
      "New /paper-trading route. Start a session against real Coinbase BTC-USD prices, open long/short positions sized by risk %, watch them tick on every new closed candle. No real money, no leverage math, no liquidation — just the part of trading the trainer can teach honestly.",
      "Reuses the v4.1 portfolio engine end-to-end. openPosition / closePosition / advanceTo / positionMarkPnl all operate on the same PortfolioSession shape; they don't care that the candles came from a Coinbase REST poll instead of the synthetic generator. ~80% of v5.0 is reuse; the new bits are lib/live-data.ts (the Coinbase fetcher) and lib/use-live-polling.ts (the tick loop hook).",
      "Picker for candle width: 1m / 5m / 15m / 1h. Poll cadence scales — 5s tick at 1m, 60s tick at 1h. Closed-candle-only (no ticker poll between bars) so the chart and SL/TP resolution stay in lockstep.",
      "Connection-status pill on the page header: Live / Fetching / Reconnecting with exponential backoff. Lose your connection, the badge flips and counts down to retry; reconnect and the polling loop catches up on any candles you missed.",
      "Session persists to trainer.livePositions.v1 (separate from the synthetic /portfolio session at trainer.openPositions.v1). Refresh mid-session and you pick up where you left off. The bundle-hazard pattern from v4.1.1 is preserved — storage.ts inlines the key string instead of importing it.",
      "End-of-session summary: realized P&L, trade count, TP/SL/manual breakdown, win rate. No challenges or scoring — live markets don't have a 'right answer' the trainer can score against.",
      "Single-symbol BTC-USD only at launch. Multi-symbol + correlation hints (parity with /portfolio's 5-symbol basket) is v5.1.",
      "13 new unit tests for the Coinbase fetcher (request URL contract, OHLCV parsing, dedupe, sort, since-time filter, rate-limit cap). useLivePolling hook tests deferred until @testing-library/react is on the devDep list — covered by browser smoke testing in v5.0.",
    ],
  },
  {
    version: "4.1.8",
    date: "2026-05-29",
    title: "Learn collapse + card-show + all 17 chart-tools visuals authored",
    highlights: [
      "Learn no longer dumps 57 nodes in a 6000px wall. Only the current module's path is expanded; the other 9 modules are compact section cards you can click to peek inside. Page is short by default; expand on demand.",
      "Clicking a node now opens a 'card show' preview right under it — term name, simple definition, why-it-matters preview, and 'Read full lesson →' / Close buttons. No navigation away until you want it. Cards have a pointer triangle visually connecting them to the node.",
      "All 17 missing chart_tools Learn visuals authored: key_mas, ma_crossover, stochastic, williams_r, atr, keltner, volume_profile, obv, cvd, fib_extension, trend_line, channel, pitchfork, ichimoku, pivot_points, donchian, parabolic_sar. The chart-tools category is now visually complete — every term renders an example chart, not a text-only definition.",
      "Each spec is illustrative, not a faithful indicator simulation — the goal is a recognisable shape so the term connects to a picture. Diagonal-line tools (trend_line, channel, pitchfork) are faked with per-candle line values; ichimoku ships with a simplified tenkan + kijun + cloud; volume_profile uses POC/HVN/LVN levels since the chart layout doesn't support a sideways histogram.",
    ],
  },
  {
    version: "4.1.7",
    date: "2026-05-29",
    title: "First-user feedback pass — Learn path, tutorial examples, portfolio zoom + account size, chart-tools help",
    highlights: [
      "Learn redesigned as a Duolingo-style path. One node per term, vertical scrolling rail with slight zigzag offsets, section headers between modules, current node highlighted and pulsing, mastered terms in green. The expandable-module list is gone — the path replaces it. Section headers keep the 'Start course' button for modules with Teach/Practice/Test steps.",
      "Tutorial spot vs. perp explanation now ships a concrete worked example: $1,000 on spot loses $100 in a 10% drop, while $1,000 of margin on a 10× perp liquidates to zero on the same move. The conceptual list of pros/cons is still there above; the worked example replaces 'just trust me on this.'",
      "Portfolio simulator: the chart no longer auto-zooms on every '+1 candle' click. Internally, Chart gained an autoFit prop (default true preserves Practice behaviour); /portfolio sets it false and forces a remount on symbol switch so each tab still fits on first render. Manual zoom now sticks.",
      "Portfolio simulator: starting account size is editable on the empty-state screen and shown in the active-session header next to PnL and Open risk. Persists via the same default the Practice form reads, so editing in one place applies in the other.",
      "Indicator toggle bar gains a '?' button that opens a quick-reference modal — five cards, each with the indicator's one-line description, a tiny MiniChart example, what it tells you, and a deep link to the full Learn term. Reduces the cold-start tax on the toggle bar without crowding the chart.",
    ],
  },
  {
    version: "4.1.6",
    date: "2026-05-29",
    title: "Procedural-recipe backfill — all 10 setup types now generatable",
    highlights: [
      "Seven new procedural recipes: support_breakdown, overextended, liquidity_sweep, clean_retest, leverage_trap, news_volatility, no_setup. Each is shaped to teach exactly the lesson its name implies — support_breakdown gives the structural-flip short, liquidity_sweep gives the wick-and-reclaim long, leverage_trap gives the violent two-sided whip after a tight coil, etc.",
      "The Practice page's 'Generate' button (which respects the active setup-type filter) can now produce a fresh chart for any of the ten setup types in the SetupType union. Previously only three setup types had recipes; the other seven silently fell back to a random recipe.",
      "Every recipe includes a complete idealDecisionPlan and outcome notes so scoring, the post-attempt review, and the AI prompt all have what they need. No 'partial' recipes ship.",
      "Test coverage extended to all 10 setup types — Scenario shape, candle OHLC integrity, valid context, deterministic per (setupType, seed). Test count: 107 → 114.",
    ],
  },
  {
    version: "4.1.5",
    date: "2026-05-28",
    title: "Test coverage backfill — curriculum + procedural-scenarios",
    highlights: [
      "Pinned 14 cases on lib/curriculum's pure helpers: currentModule, nextUnreadInModule, moduleForTerm, isStepComplete, nextStepInModule. The Practice and CoursePlayer surfaces all depend on these — silent drift in 'what's next' or 'is this step done' would surface as broken navigation. Pinning protects against curriculum edits accidentally changing semantics.",
      "Pinned 11 cases on lib/procedural-scenarios. Every recipe produces a Scenario with positive volume, OHLC consistency, valid context, and a frozen idealDecisionPlan. Determinism per (setupType, seed) is locked. The 'unknown setupType' branch falls back to a random recipe rather than throwing — pinned so a future 'throw on unknown' refactor surfaces as a failing test rather than a Practice-page crash.",
      "lib/htf.test.ts review: findHTFDecisionIndex + synthesizeHTF + htfBucketSize were already covered. Coverage gap on htf was stale.",
      "Test count: 82 → 107.",
    ],
  },
  {
    version: "4.1.4",
    date: "2026-05-28",
    title: "Scenario Studio gains an Auto-generate HTF button",
    highlights: [
      "Scenario Studio now has an Auto-generate HTF section. One click runs lib/htf's synthesizeHTF over the visible+hidden candles, computes the decision index, and renders an HTFChart preview so the author can sanity-check the result before pasting.",
      "When HTF is generated, the output literal includes higherTimeframe / higherTimeframeCandles / higherTimeframeDecisionIndex so the same chart shows on every build instead of being re-synthesised at runtime. Clearing the HTF removes those fields from the literal.",
      "Stale-HTF guard: changing the LTF candle moves, base price, seed, interval, or timeframe automatically clears the saved HTF so the author can't paste a literal whose HTF was derived from candles no longer in the output.",
      "Closes another v4.0-era deferred item. Original-dump backlog still owes 17 missing chart specs, steps[] for term-list curriculum modules, procedural recipes for 7 setup types, and test coverage for lib/curriculum + lib/procedural-scenarios + lib/htf edges.",
    ],
  },
  {
    version: "4.1.3",
    date: "2026-05-28",
    title: "Context-first drill — the HTF-before-LTF reflex, as a drill",
    highlights: [
      "New 'Context first' drill at /learn/context-first. Ten rounds: the HTF chart appears for five seconds, hides, you call the trend (up/down/range), then the HTF and LTF reveal side-by-side with a one-line note on what the HTF told you. Trains the same reflex v4.0 made structural — read the bigger picture first.",
      "Eligible scenarios are anything in the library with usable HTF data: authored when available, otherwise synthesised through the same downsample lib/htf already powers /practice with. Scenarios without a clean HTF step (e.g. daily-timeframe with no native weekly) get filtered out of the round pool.",
      "Sits beside Speed-read drills inside the Learn hero so the two reflex drills are discoverable together. They're shaped the same — 10 rounds, 5-second reveal — but they target different reflexes: Speed-read for pattern recognition, Context-first for timeframe discipline.",
      "Closes out one of the v4.0-era deferred items. Backlog from the original dump still includes the Studio 'auto-generate HTF from LTF' button, 17 missing chart specs, procedural recipes for 7 setup types, and steps[] authoring for the term-list curriculum modules.",
    ],
  },
  {
    version: "4.1.2",
    date: "2026-05-28",
    title: "Second portfolio challenge + CoursePlayer scoping resolved",
    highlights: [
      "Second portfolio challenge: 'Finish above water.' Open at least 3 positions and end with positive realized P&L. The composition challenge ('Run 5 concurrent trades') taught process; this one teaches outcome — and the bridge between them is exactly the lesson that 'good composition is necessary but not sufficient.'",
      "Session summary now lists which challenges cleared (✓) and stamps each one to trainer.portfolioChallenges.v1. Challenges accumulate across sessions so once you've cleared a challenge it stays cleared even if a later session doesn't repeat the feat.",
      "ChallengeBanner stays focused on the primary challenge so the simulator's main goal is still legible. Future challenges layer onto SessionSummary without crowding the active surface.",
      "CoursePlayer scoping question (open since v4.0): decided to keep LearnPath as the default Learn surface. CoursePlayer remains opt-in via /learn/course/[moduleId] — less disruptive to existing navigation, and future revisions can promote the 'Start course' CTA more prominently on LearnPath cards if data shows it's underused. This unblocks v4.2 prep.",
    ],
  },
  {
    version: "4.1.1",
    date: "2026-05-28",
    title: "Portfolio polish — the named challenge, a curriculum module, and indicators on the simulator chart",
    highlights: [
      "The 'Run 5 concurrent trades for 7 days' challenge — the one the original v4.1 spec named — now ships as a portfolio-native challenge. Goal banner on /portfolio shows progress (positions opened / 5) and lights up green with a ✓ when you finish a session with at least 5 positions and a portfolio_balanced score. Completion stamped to trainer.portfolioChallenges.v1 so it survives subsequent sessions.",
      "New 'Portfolio thinking' module in the curriculum browser, pointing at the portfolio_risk Learn term added in v4.1.0. Term-list style for now — the hands-on practice is the simulator itself, not a Practice-page scenario, so a Teach/Practice/Test loop would have been forced.",
      "Indicator overlays now work on /portfolio's chart the same way they do on Practice. Same toggle bar, same persisted defaults, RSI/MACD sub-panels included. Useful even on synthesised data because the math is the math — your indicator habits transfer to the simulator surface.",
      "Behind-the-scenes: lib/portfolio-challenge.ts as a small new module so the existing single-scenario DrillSet shape didn't have to bend. New 4 challenge-evaluator tests bring the v4 portfolio test suite to 28.",
    ],
  },
  {
    version: "4.1.0",
    date: "2026-05-28",
    title: "Portfolio simulator — concurrent positions on one 7-day clock",
    highlights: [
      "Brand-new Portfolio simulator at /portfolio. One master timeline (4h candles × 7 days = 42 ticks), five symbols (BTC, ETH, SOL, DOGE, LINK), and you open positions concurrently across all of them. The whole basket ticks together when you advance time — the lesson is what 'concurrent' actually costs you when symbols correlate.",
      "Multi-symbol generator with a market-beta model: each symbol's drift = ρ × shared_market + sqrt(1-ρ²) × idiosyncratic_noise. BTC and ETH come out highly correlated (~0.6–0.7 realised on close prices), SOL middling, DOGE weaker, LINK an actual diversifier (~0.25 designed). Deterministic per seed.",
      "Live 'Correlation hint' banner flags same-direction pairs whose realised ρ exceeds 0.7 over the candles seen so far. The hint fires while the session is still active so you can adjust — not just after.",
      "End-of-session 'Portfolio risk' score (10 pts). Penalises total session risk above 5% (−1 per pp over, capped at −5) and same-direction overlap on high-correlation pairs (−3 per pair). Pairs with a positive portfolio_balanced tag when both checks pass.",
      "Dashboard gains a Portfolio simulator card showing 'No session' / N open positions / total risk / running PnL, and click-through to the simulator. The simulator state persists to trainer.openPositions.v1, so refreshes resume mid-session.",
      "New Learn term: portfolio_risk (Risk Management). New principle: 'Diversify your bets, not your label.' Two new MistakeTags (portfolio_overconcentrated, portfolio_correlated_overlap) and one positive tag (portfolio_balanced).",
      "Next in the v4 arc: v4.2 (AI engine — AI scenario generation + tailored drills) and v4.3 (backend foundation — optional cloud sync + hosted AI key).",
    ],
  },
  {
    version: "4.0.3",
    date: "2026-05-28",
    title: "Chart tools scoring — your thesis gets credit for naming the indicator",
    highlights: [
      "New optional 'Chart tools' scoring category (5 pts). Opt-in: only appears on scenarios authored with availableIndicators set and only when you took a non-wait position. Tiered: 5/5 if your thesis names an available indicator, 2/5 if you had one toggled on but didn't write about it, 0/5 (and an 'Ignored available indicator' tag) otherwise.",
      "New mistake tag: ignored_indicator. Fires when a scenario was built around a specific chart tool — say a MACD divergence — and you neither turned it on nor referenced it. The tag's review note points you straight back to the Indicators bar.",
      "New Attempt.indicatorState snapshot — captures which overlays were on at submit. Frozen into the saved attempt so the review and the AI prompt always know what you were looking at, even months later.",
      "AI prompt gains an INDICATORS block: which tools the scenario teaches around, which you had on, and the chart_tools score line. The AI review can now say 'you had RSI off in a scenario built around RSI divergence' instead of guessing.",
      "Bumped SCORING_VERSION to 3.0.0. Old attempts keep their breakdown verbatim — the new category just doesn't appear on them. The Attempt.scoringVersion field has been pinning attempts to their rule set since v1.5, so journals stay coherent across the bump.",
    ],
  },
  {
    version: "4.0.2",
    date: "2026-05-28",
    title: "Practice chart overlays — five toggleable indicators on the live chart",
    highlights: [
      "Five toggleable indicators on the Practice chart: EMA (20/50/200 bundle), Bollinger Bands (20, 2σ), VWAP, RSI (14), and MACD (12/26/9). EMA, BB, and VWAP overlay the main candle chart; RSI and MACD render in compact sub-panels below it.",
      "A compact 'Indicators' bar sits above the chart with one toggle per indicator. Toggles are session-local — flipping RSI on for one scenario doesn't change what you see by default tomorrow.",
      "New Settings → 'Default chart overlays' section: pick what comes on by default whenever you open a Practice scenario. Persists to trainer.indicators.v1; missing keys default to off so future indicators don't auto-enable.",
      "Indicator math lives in a new pure-function lib/indicators.ts (SMA, EMA, RSI, MACD, Bollinger Bands, VWAP) with a 20-test Vitest suite pinning warmup behaviour and numeric correctness. Wilder's smoothing for RSI; SMA-seeded EMAs to match TradingView.",
      "Overlays are hidden in Mirror mode (a moving average on a flipped chart teaches the wrong thing) and continue computing through the post-decision region once hidden candles are revealed. Next in the v4.0.x arc: v4.0.3 wires the chart_tools scoring category that rewards a thesis when it correctly references an indicator the chart actually shows.",
    ],
  },
  {
    version: "4.0.1",
    date: "2026-05-24",
    title: "Chart tools — 25 new lessons on indicators and drawing tools",
    highlights: [
      "New 'Chart Tools' Learn category with 25 terms covering the indicator and drawing toolkit every chart platform ships with: moving averages (SMA, EMA, key 20/50/200, crossovers), momentum oscillators (RSI, MACD, Stochastic, Williams %R, divergence), volatility (Bollinger Bands, ATR, Keltner), volume-based (Volume Profile, VWAP, OBV, CVD), drawing tools (Fib retracement + extension, trend lines, channels, pitchfork), and patterns (Ichimoku, Pivot Points, Donchian, Parabolic SAR).",
      "Each term gets the full template: simple definition, why it matters, worked example, common mistake, scoring connection, plus a quiz. The most visual terms (SMA, EMA, Bollinger, RSI, MACD, Fib, VWAP, divergence) also got hand-authored chart specs so you see the indicator drawn on a chart, not just described.",
      "MiniChart gained three new optional fields: lines (price overlays for EMAs and VWAP), bands (filled envelopes like Bollinger), subPanels (oscillators like RSI, histograms like MACD). The chart spec system that powers every Learn example now scales to indicator content.",
      "Two new curriculum modules with Teach → Practice → Test loops: 'Chart tools — momentum & trend' (5 steps: MAs, RSI, MACD, divergence, Bollinger) and 'Chart tools — volume & drawing' (5 steps: VWAP, Volume Profile, Fib, trend lines, channels). Each step uses an existing real-data scenario where the indicator's read would have been the lesson.",
      "First sub-release in the v4.0.x chart-tools series. Next: v4.0.2 wires toggleable indicator overlays onto the Practice chart; v4.0.3 adds optional scoring that rewards your thesis when it correctly references an indicator on the chart.",
    ],
  },
  {
    version: "4.0",
    date: "2026-05-24",
    title: "Multi-timeframe is now a first-class skill",
    highlights: [
      "Higher-timeframe chart on every scenario. The HTF panel used to appear only when a scenario shipped with authored HTF data. Now every scenario has one — when authored data is missing, the trainer synthesises an HTF series by downsampling the LTF candles into larger buckets (4× or 6× depending on the timeframe). Synthesised HTF panels show a quiet 'synthesised from {timeframe} candles' note so you know it's derived, not fetched.",
      "Layout unchanged from a user's POV but reaches everywhere now. HTF sits to the right (~1/3 width) on desktop; stacks above the LTF on narrower viewports. Mirror mode hides HTF (flipping a downsample is doubly confusing).",
      "New Learn term: HTF alignment. Reading the higher timeframe before the lower one is the single best habit a beginner can build, and the trainer didn't teach it explicitly before. Lives under chart_reading; full why-it-matters + example + common mistake.",
      "Foundations course gains a 4th step: HTF alignment. Practice scenario chosen so the HTF makes the read easy; test scenario chosen so the LTF would tempt a counter-trend entry but the HTF tells you to wait. Pass at 70 to mark the step complete.",
      "Opens the v4 'multi-everything' arc. Next: v4.1 portfolio thinking (concurrent positions, total risk budget, correlation hints), v4.2 AI engine (AI scenario generation + tailored drills), v4.3 backend foundation (optional cloud sync + hosted AI key).",
    ],
  },
  {
    version: "3.5",
    date: "2026-05-24",
    title: "Voice consistency — small copy pass",
    highlights: [
      "Codebase-wide voice audit against the style guide added to the roadmap. The trainer turned out to be remarkably disciplined already — only five string edits across three files needed fixing. The rest of the surfaces (review headlines, achievements, lesson terms, mascot empty states, dashboard widgets) already read in one voice.",
      "Tutorial: step 10 retitled 'Decisions are scored, not luck' (was 'We score the decision, not the luck'). Step 2 + step 10 body now say 'the trainer' instead of 'this app' for name consistency.",
      "Diagnostic: the encouragement after a missed fakeout question stopped saying 'don't worry' (patronising) and now reframes the question itself as the diagnostic's job, not yours.",
      "Practice form: the direction-field tooltip now says 'In the trainer, wait is rewarded' instead of 'In this app'. Tiny but the trainer reads as one voice now, end-to-end.",
      "CONTRIBUTING.md gained a 'voice' section pointing at the full style guide in the roadmap so future contributors don't drift.",
    ],
  },
  {
    version: "3.4",
    date: "2026-05-24",
    title: "Scenario Studio — author scenarios without writing JSON",
    highlights: [
      "New /studio route (hidden from nav, URL-only). Sketch a scenario by editing a list of per-candle moves — drift + volatility per bar — and watch the chart redraw live. Reuses the same buildSeries primitive that v3.0's procedural generator runs on, so the studio output is shape-identical to the rest of the library.",
      "Edit everything inline: metadata (id, title, symbol, timeframe, difficulty, setup type, base price, seed), visible candles + hidden candles, key levels, preferred decision, ideal decision plan (entry / stop / TP / leverage / risk%, thesis, invalidation), and all the narrative fields (market context, neutral notes, learning focus, outcome description + takeaway).",
      "One-click TS export. The bottom panel renders a fully-formatted buildRealScenario({...}) literal — paste it straight into lib/scenarios-real.ts inside REAL_SCENARIOS and it works. Cuts per-scenario authoring from ~30 min of hand-typing JSON to ~5 min of slider-tweaking.",
      "Closes the v3 'make the trainer trainable' arc. With v3.0 (smart rotation + procedural), v3.1 (replay + growth + revisit), v3.2 (Teach → Practice → Test course), v3.3 (cleanup + tests), and now v3.4 (authoring), every later release that wants new scenarios has the tool to ship one in minutes.",
    ],
  },
  {
    version: "3.3",
    date: "2026-05-24",
    title: "Foundation work — the cleanup release (internal, no user-facing change)",
    highlights: [
      "Practice page split. The 1,337-line app/practice/page.tsx had eight one-purpose helpers stitched into it (RestraintNudge, MacroBriefCard, CollapsibleNotes, MirrorToggle, ModeToggle, ScenarioMeta, DrillStatusBanner, CourseBanner). All moved to components/practice/ with behaviour unchanged. The file is now ~1000 lines, mostly the actual PracticeFlow logic.",
      "Vitest installed. Smoke tests added under lib/__tests__/ for the rule engines that future versions all depend on: scoring (estimateLiquidationPrice + scoreDecision), equity (simulateEquityCurve), skills (computeSkillScores + weakestSkill/strongestSkill). 13 tests, run with `npm test`. The bar is 'would a breaking change here silently miscompound saves' — not exhaustive coverage.",
      "CONTRIBUTING.md. One-page doc covering storage key conventions, scenario shape, component conventions, versioning discipline, where to add tests. The patterns this codebase has accumulated, written down once so future versions don't drift.",
      "Internal release — nothing changes for the user. Sets up the next three releases (v3.4 scenario authoring tooling, v4.0 multi-timeframe, v4.1 portfolio thinking) which all touch the practice flow.",
    ],
  },
  {
    version: "3.2",
    date: "2026-05-24",
    title: "Lesson-coupled curriculum — Teach → Practice → Test loop",
    highlights: [
      "Curriculum modules become real courses. Foundations and Risk-and-sizing are now interactive courses with stepped lessons — read the concept, practice it with hints on one scenario, then pass a different scenario at 70+ to unlock the next step. Other modules keep the existing term-card view for now (more authoring to follow).",
      "New /learn/course/[moduleId] route + CoursePlayer. Each step shows the Teach card inline (Simple definition + why it matters), then Practice and Test panels with deep links to /practice. Completion is computed live from your journal — pass once, the step stays passed.",
      "Course banner on the Practice page. When you arrive from a course, you see a clear 'Course · test' (or practice) chip showing which step you're on and a one-click Back-to-course link. For tests, the banner flips to green when your best score crosses the passing threshold.",
      "LearnPath surfaces courses. Modules with steps[] get a ★ Course pill on the row header and an Open card inside the expanded body. Module rows without a course still show the legacy term list — backward compatible.",
      "Continues the v3 'make the trainer trainable' arc. Up next: v3.3 — The Cleanup Release. Splits the largest file, adds Vitest with smoke tests for the scoring engine, and a contributing.md so future versions don't drift.",
    ],
  },
  {
    version: "3.1",
    date: "2026-05-24",
    title: "Review-as-coach — replay scrubber, growth view, revisit prompts, scenario snapshots",
    highlights: [
      "Replay scrubber on every attempt. Open any past attempt and drag the slider to reveal the hidden candles one at a time — see what price actually did after your entry, not just the final outcome. Live overlay tells you which candle hit TP / SL / liquidation as you scrub past it.",
      "Scenario snapshots. Every saved attempt now embeds a frozen copy of the scenario (candles, key levels, ideal plan, outcome notes). Means procedural scenarios — which used to disappear on page reload — now stay in your journal forever. Also future-proofs old attempts if the scenario library changes between versions.",
      "Growth view at /journal/growth. Week-by-week per-skill sparklines plus a 'this month vs. last month' headline calling out your biggest gain and worst slip. Climbing lines are the proof you were looking for. New ↗ Growth link from the journal stats row.",
      "Revisit prompts on the Dashboard. Surfaces one old attempt worth re-reading with fresh eyes — either something you annotated 2+ weeks ago, or an old sub-60 score that's gone untouched. The old failures are usually the easiest lessons to spot the second time.",
      "Second release of the v3 'make the trainer trainable' arc. Up next: v3.2 turns the curriculum into a real course (Teach → Practice → Test loop per module step).",
    ],
  },
  {
    version: "3.0",
    date: "2026-05-24",
    title: "Scenario variety release — smart rotation, procedural generation, freshness tracking",
    highlights: [
      "Smart rotation. pickNextScenario stops cycling the same handful and prefers scenarios you haven't SEEN recently (not just attempted) — skipping past a chart still pushes it to the back of the queue. Inside drills and filters too. Practice 30 days in a row without seeing the same setup twice in a row.",
      "Procedural scenarios. A new ✦ Generate button on the Practice filters bar produces a fresh, never-before-seen scenario on demand. v1 covers three setups (trend continuation, failed breakout, range chop) across BTC, ETH, and SOL on multiple timeframes. Each one is a complete trainable scenario with key levels, ideal decision plan, and outcome notes — not just noise.",
      "Procedural badge. When a procedural scenario is loaded, the title gets a small ✦ Procedural pill so you know it's generated, not historical. Attempts on procedural scenarios save to your journal like any other.",
      "Freshness tracking. Internal: every scenario load stamps a 'seen at' timestamp in localStorage, separate from your attempt history. Feeds smart rotation and unblocks future 'you haven't tried a clean retest in 3 weeks' nudges.",
      "Begins the v3 arc — 'make the trainer trainable.' Next up: review-as-coach (longitudinal growth + replay scrubber), then a lesson-coupled curriculum where each module step is Teach → Practice → Test.",
    ],
  },
  {
    version: "2.9",
    date: "2026-05-24",
    title: "What-if sandbox, weekly digest, drill completion, trading defaults",
    highlights: [
      "What-if sandbox on the review. After submit (and on any past attempt in the Journal), nudge entry / stop / TP / leverage / risk % via steppers and watch the score recompute live with per-category deltas. Your saved attempt isn't touched — this is the sandbox you wanted when you saw '−1' next to 'Stop placement.'",
      "Weekly digest on the Dashboard. A 4-up strip below the equity curve: attempts this week (+ delta vs. previous 7d), avg score (+ delta), days active, and the most-tagged mistake. Pure read of existing data, hidden when there's nothing in the trailing 14 days to show.",
      "Drill completion summary. When you hit the drill's targetAttempts, the active-drill banner swaps to a green celebration card with the skill-focus delta (drill score vs. everything before it), the drill avg, and three CTAs — mark complete, pick a new drill, or continue free practice. Drills no longer fizzle out into nothing.",
      "Trading defaults in Settings. Risk %, leverage, and account size now have user-set defaults under Settings → Trading defaults. The DecisionForm and the guided wizard both prefill from these so you stop re-entering '1 / 3 / 1000' every scenario.",
    ],
  },
  {
    version: "2.8",
    date: "2026-05-24",
    title: "Learn becomes a path; Glossary is now its own top-nav page",
    highlights: [
      "Learn is now a single path. The Curriculum/All-terms tab toggle is gone. Landing on /learn shows one hero — 'Module N of 7 — {title}, Next up: {term}' — and a rail of 7 module rows beneath it. The current module is expanded with its term cards; completed and upcoming modules are dimmed but still clickable for anyone who wants to skip ahead.",
      "Refresher mode. Once every term has been read at least once, the hero swaps to 'You've read everything once — re-open {term},' picking the term tied to your weakest skill so the next pass lands where it actually helps.",
      "Glossary is now a top-nav page at /glossary. Same search, same category and mastery filters as the old 'All terms' tab — just discoverable from anywhere, including while you're staring at a chart during practice.",
      "Term detail unchanged. The worked example, related mistake tags, quiz, and related-term carousel render the same on both /learn?term=X and /glossary?term=X — extracted into one shared component (no copy-paste duplication).",
      "All deep links keep working. ForceMicroLesson, AttemptDetail's recommended-term link, the Training Path's recommended lesson — every existing /learn?term=X link still lands on the term detail. Nothing in storage migrated; readTermIds keeps its old key.",
    ],
  },
  {
    version: "2.7",
    date: "2026-05-24",
    title: "Bookmarks page, per-skill trends, compare attempts, principle-of-the-day",
    highlights: [
      "Bookmarks page. /journal/bookmarks lists every scenario you've starred with one-click 'Open in Practice' and inline unbookmark. Replaces the hidden 'bookmarked only' filter as the primary surface.",
      "Per-skill trend chart on the Journal. Below the stat cards, one sparkline per skill (patience, stop placement, risk-reward, etc.) shows the rolling average across your recent attempts. Climbing lines are the proof you wanted.",
      "Compare two attempts. From any journal entry, pick a second attempt (defaults to your most recent on the same scenario) and see a side-by-side diff of decision fields, score, tags, and outcome. Best for measuring the same scenario at two different times.",
      "Principle of the day on the Dashboard. One of 10 principles rotates daily — small reason to come back when nothing else is calling you.",
      "Cleanup: removed a leftover ContinueHero component that hadn't been wired up since the Dashboard restructure.",
    ],
  },
  {
    version: "2.6",
    date: "2026-05-24",
    title: "Visual redesign — warm palette, light + dark, owl mascot, restructured Dashboard",
    highlights: [
      "Dual themes. New warm-dark default (espresso/cream, not blue-black) plus a paper-light option. Theme toggle in the header (sun/moon icon) persists per browser. Boot script applies it before paint so there's no flash.",
      "New accent — warm gold (#D4A574) replaces the corporate blue. Charts, buttons, badges, and highlights all shift to the warmer palette. Cleaner, more memorable, less generic SaaS.",
      "Owl mascot. A hand-drawn SVG owl with six moods (idle, watching, happy, thinking, sleeping, confused) appears at moments where the app should feel personal: Welcome step 1, the Dashboard greeting, the AI coach avatar, the empty Journal, the cooldown card.",
      "Dashboard restructured. Tabs are gone. A continuous scroll: mascot greeting + sparkline of last 10 scores → today's plan (1 lesson, 1 quiz, 3 attempts) → big equity curve → weakest skill + recommended drill → recent attempts → achievements row.",
      "Borderless hierarchy. Most sections lose their cards. Type and spacing do the work of separating content — the only bordered things are inputs, charts, and a few intentional callouts. The 'wall of equal-weight cards' is gone.",
      "Tabular numerics. Big numbers (equity, score, R:R) now use tabular-nums so they line up across rows and don't dance when the value changes.",
    ],
  },
  {
    version: "2.5",
    date: "2026-05-23",
    title: "AI review and coach chat (bring your own Anthropic key)",
    highlights: [
      "AI Review card: after each submit, a personalised 3-paragraph review streams in below the worked example. It names your numbers, contrasts with the ideal plan, and gives one concrete habit for next time. Cached per attempt — revisiting the journal doesn't re-bill.",
      "AI Coach chat: a collapsible chat under the review where you can ask follow-up questions about that exact trade — \"why was my stop too tight?\", \"explain invalidation again,\" anything. Multi-turn history persists per attempt.",
      "Bring your own key. Off by default; toggle on in Settings → AI features. First-time enable shows a consent modal explaining what gets sent (your decision, the scenario, your score, your chat history), where the key is stored (browser localStorage), and rough cost (~$0.005/review on Haiku, ~$0.02 on Sonnet).",
      "Model selection. Haiku 4.5 by default (fast, cheap). Switch to Sonnet 4.6 in Settings for a deeper review.",
      "Built for hosted later. The transport (browser→Anthropic direct vs. server-proxy) is pluggable behind a single client interface — when the app moves off local-only, the AI surfaces won't change.",
      "Errors handled inline. Bad key, rate limits, network blips all surface in the card with a Retry button; the rest of the review panel (rule-based score, BestDecisionCard) keeps working.",
    ],
  },
  {
    version: "2.4",
    date: "2026-05-22",
    title: "Nine grab-bag features — sizing math, thesis critique, drills, macros, badges, more",
    highlights: [
      "Inline position-sizing math on the decision form: when you set risk %, entry, and stop, the form tells you exactly what dollar loss your plan implies and what position size matches. This is the math beginners get backwards most often.",
      "Thesis check: a small structural critique of your thesis and invalidation text appears beside your decision after submit. Flags theses without a level, invalidations that read like feelings, missing direction. No LLM — just keyword + numeric pattern checks.",
      "Cooldown after losing streak: three consecutive sub-60 attempts in a session triggers a forced 2-minute break with a one-sentence reflection prompt. Trains the single most valuable real-trading habit: step away when you're cold.",
      "Mirror mode: a chart toggle that flips the candles vertically — long looks like short, support becomes resistance. Same structure, no directional bias. Display-only; toggle off to submit.",
      "Achievements: 14 local-only milestones (First steps, Five for five, Patience under pressure, Setup sampler, Comeback, Marathon: 100 attempts, …). No leaderboard, no social — just markers in the Performance tab.",
      "Annotated replay: any attempt in the journal accepts new timestamped notes. Come back months later, add 'I now see the lower high I missed.' The journal turns into a living surface, not a graveyard.",
      "Macro context briefings: each scenario now shows a one-paragraph card explaining what was happening in crypto/macro at the time (yen carry unwind, ETF approval, LUNA collapse, etc). Grounds beginners in the why behind historical setups. Derived from candle timestamps — no per-scenario authoring.",
      "Diagnostic Before/Now: retake the diagnostic and see a side-by-side of which questions you fixed, which you regressed on, and which stayed steady. Concrete skill-growth proof instead of an abstract score average.",
      "Speed-read drills: new /learn/drills route. Ten 5-second flashcards. Chart appears, then hides; you answer from memory. Builds the chart-reading reflex the slow form trains slowly.",
    ],
  },
  {
    version: "2.3",
    date: "2026-05-21",
    title: "Beginner onboarding pass — five fixes for the first 20 minutes",
    highlights: [
      "Welcome step 0: 'Is this trainer for you?' — spot vs futures/perp framing so a beginner who only knows buy-and-hold knows immediately what kind of trading the rest of the lessons assume.",
      "New caveat step near the end of Welcome: what this trainer trains (chart reading, decision discipline) and what it doesn't simulate (emotions, fees, funding, slippage, news shocks). When you graduate, start tiny on spot before futures.",
      "Diagnostic Q1 is now visual — a chart of an uptrend instead of a text price stream. Risk math moves to Q2. Wrong answers get a normalising line ('most beginners miss this — that's why it's here') before the explanation so failure doesn't feel like rejection.",
      "Post-diagnostic 'Risk warning' renamed to 'First focus area' with coaching-tone body copy. Same recommendation, less judgment.",
      "Practice page: setup-type filter is hidden for the first 10 attempts (with a 'Show anyway' override). When shown, each setup name has a tooltip explaining the pattern in one sentence. Beginners can't filter by what they don't yet understand.",
      "Watch-me walkthrough on the first Practice visit: instead of asking 'what's your read?', the app fills the form itself and narrates each field on a curated SOL pullback scenario. Skip button prominent. Settings has a 'Reset walkthrough' option to re-run it.",
      "Practice match-count copy: '53 scenarios match' → '53 to choose from. Click Random or Next to start.' Removes the quota feel.",
    ],
  },
  {
    version: "2.2",
    date: "2026-05-21",
    title: "Equity curve, higher-timeframe context, worked examples",
    highlights: [
      "Dashboard › Performance: simulated equity curve. Compounds each attempt's PnL at your stated risk % so you can see whether the decisions you've been making would have grown a $10k account or shrunk it. Decision quality only — fees and funding aren't modeled.",
      "Practice: every scenario now surfaces a higher-timeframe thumbnail (1d when the main chart is 6h, etc.) beside the main chart. A dashed line marks where you are. Stops the #1 beginner trap of calling a low-timeframe pullback bullish inside a higher-timeframe downtrend.",
      "Review: 'What a strong decision looked like' card sits above the breakdown after submit. Curated entry / stop / TP / R:R / leverage / risk %, plus a 1–2 sentence thesis and invalidation. Compare to your own decision on the left side to see what 95/100 actually looks like.",
      "Backfill in progress: HTF candles and worked-example plans are being authored scenario-by-scenario. Until a scenario gets its data, both surfaces hide gracefully.",
    ],
  },
  {
    version: "2.1",
    date: "2026-05-19",
    title: "Attention, teaching, focus — 5 phases",
    highlights: [
      "Post-attempt: one-sentence headline (score + strongest + weakest) above a collapsed breakdown. Cut the post-submit fatigue wall from ~700px to ~250px before scroll.",
      "Color semantics audit: accent (blue) reserved for primary actions only. Strongest skill → muted (it's context). Weakest skill → warn (focus area, not failure). Mistake-chip links stripped to underline. Bookmarked star → warn gold. JargonTip '?' buttons → muted (no longer look like required-field markers).",
      "Daily streak + practice goal: 🔥 chip in header (current streak · today's progress). Defaults to 3 attempts/day, configurable in Settings. Goes 💤 when broken-but-recoverable. Mobile sees it on the Dashboard.",
      "Spaced-repetition micro-lessons: any mistake tag fired 3+ times in your last 10 attempts triggers a forced refresher with the matching Learn term — sit, read, click 'Got it', then see your score. Visiting the term resets the cooldown. Toggleable in Settings.",
      "Dashboard restructure: 3 tabs (Overview / Performance / History) with URL-hash deep links. Cut DataManagement to /settings, merged the standalone 'repeated mistakes' card into the main mistakes list (inline 'Review (2 min)' buttons), removed Learn-progress card. Dashboard dropped from ~10 stacked sections to 1 hero strip + 1 tab panel.",
      "Settings: new /settings route + gear icon in header. Hosts data export/import, daily-goal slider, micro-lesson toggle.",
      "Cleanup pass: fixed Tabs a11y (panels render with hidden attribute, all aria-controls resolve), pickForcedLesson now sorts tags by priority so the most-account-threatening lesson fires first, /welcome no longer shows full chrome.",
    ],
  },
  {
    version: "2.0.1",
    date: "2026-05-18",
    title: "QoL pass — bug fixes, journal PnL, bookmarks",
    highlights: [
      "Fixed: Learn term detail (?term=X) didn't open from deep links. Every 'Open lesson →' link now works.",
      "Fixed: scoreTarget was misclassifying partial-credit notes as strengths — coaching advice now correctly appears in 'What to improve'.",
      "Fixed: 12 scenarios had stale context.currentPrice values (up to 6.5% off) used for entry-chasing scoring and the form 'current price' hint.",
      "Fixed: 3 managed scenarios had prompt text that didn't match actual price action at the management point (e.g. claimed +1R when price was -1%).",
      "Fixed: 'Continue your training' hero stopped pointing forever to 'Take the diagnostic' for users who'd skipped it. Active drills and recent sessions now take priority.",
      "Fixed: ETH/USDT + SOL/USDT old synthetic symbols normalized to /USD so filters don't fragment.",
      "Fixed: Setup-type filter no longer shows options with zero scenarios.",
      "Fixed: Journal renders 'Removed scenario (id)' instead of raw ID when a scenario is gone.",
      "Tutorial step 8 now has a side-by-side example: Trade A (good plan, lost, 85/100) vs Trade B (no stop, won, 30/100).",
      "Journal page: header now shows total attempts, closed trade count + W/L, cumulative PnL %, and avg process score. Each row gets a PnL column.",
      "Bookmark scenarios with a star toggle. 'Bookmarked only' filter on Practice. Per-scenario attempt count + best/last score shown above the chart.",
    ],
  },
  {
    version: "2.0",
    date: "2026-05-18",
    title: "Trade management — manage the trade, not just enter it",
    highlights: [
      "After you submit an entry, you now step through hand-curated decision points as price plays out: hold / move stop to break-even / take 50% off / exit. Position size and working stop update in real time.",
      "New scoring category: 'Trade management.' Rewards protecting winners (BE stops after +1R), banking partials at key levels, letting runners run when the trend is intact. Penalises exiting too early, holding through invalidation, failing to protect.",
      "New mistake tags: exited_too_early, let_winner_become_loser, held_through_invalidation, failed_to_protect, managed_well (positive).",
      "Three scenarios authored with management points to start: BTC reclaims $50k retest, FTX $20k breakdown short, SOL parabolic from $24. More to come as you find the ones that teach best.",
      "Outcome calculation honours your management: partial fills compound into final P&L, moved stops change the exit level, exits at current candle close.",
      "Backwards-compatible: scenarios without management points behave exactly as v1.9. Saved attempts under SCORING_VERSION 1.5.0 keep their original score.",
      "SCORING_VERSION bumped 1.5.0 → 2.0.0. New attempts get the 2.0.0 stamp.",
    ],
  },
  {
    version: "1.9",
    date: "2026-05-18",
    title: "Mobile nav, desktop-first reframe, +23 real scenarios",
    highlights: [
      "Bottom tab bar on mobile — Dashboard / Training / Practice / Journal / Learn always one tap away.",
      "Touch-target sweep: bigger tap areas on filters, chips, and icon buttons (helps desktop clicks too).",
      "Direction: this is a study tool. Chart analysis and the decision form are designed for desktop; mobile is respectable for browsing your Journal and Learn, not for running a full practice session.",
      "Scenario library doubled: 23 new real-OHLCV setups across the four missing types — support_breakdown (May/Jun 2022 LUNA & Celsius, Nov 2022 FTX, Aug 2023, Mar 2020), overextended (Nov 2021/Mar 2024 BTC ATHs, Apr 2021 Coinbase, Jan 2024 ETF, Dec 2024 $100k, Mar 2024 SOL), clean_retest (Oct/Nov 2023 BTC $30k/$35k, Feb 2024 BTC $50k, Oct 2023 SOL, Feb 2024 ETH, May 2024 BTC), leverage_trap (Mar 2020 COVID, May 2021 Musk, Aug 2023, Jan 2024 ETF whipsaw, Apr 2024 Iran, Aug 2024 yen carry).",
    ],
  },
  {
    version: "1.8",
    date: "2026-05-17",
    title: "Onboarding — first lesson",
    highlights: [
      "New 10-step tutorial at /welcome — covers candles, direction, stops, targets, R:R, leverage, and decision quality.",
      "First-time visitors with no saved attempts are routed to the tutorial automatically.",
      "Jargon tooltips on every field of the decision form. Tap the '?' next to a label to see a plain-language definition and a link to the full lesson.",
      "Learn now has a Curriculum view: 7 modules in order, with read and mastered checkmarks.",
      "Guided Mode for your first 5 practice attempts — step-by-step wizard instead of the full form.",
      "Continue your training hero card on the Dashboard — one button that always knows the right next step.",
      "Real-data scenarios from v1.7 are live: 20 new historical setups across 4 setup types.",
      "8-question diagnostic with new trap setups for sharper profile assignment.",
      "Charts now pan and zoom without snapping back to fit.",
    ],
  },
  {
    version: "1.6",
    date: "2026-05-17",
    title: "Polish & restraint",
    highlights: [
      "Mistake tags now reflect severity — account-threatening tags stand out from minor ones.",
      "Attempt detail has a free-text reflection field (saves automatically).",
      "Practice page collapses scenario notes after submit so review stays in focus.",
      "Restraint nudge appears when you grind too many attempts in a short window.",
      "Version badge now opens this changelog.",
    ],
  },
  {
    version: "1.5",
    date: "2026-05-15",
    title: "Guided training path",
    highlights: [
      "New Training Path page with a four-question diagnostic on first visit.",
      "Six drill sets you can route into directly from Dashboard or Training Path.",
      "Skill map: 9 skills derived from your score categories and tag history.",
      "Attempt detail pages at /journal/[attemptId] with Retry similar scenario.",
      "Data management — export, import, clear journal/quiz/all.",
    ],
  },
  {
    version: "1.4",
    date: "2026-05-12",
    title: "Mistake → Learn integration",
    highlights: [
      "Central mistake-tag → Learn term map with priority ordering.",
      "Review shows one primary lesson recommendation with action buttons.",
      "Quiz attempts persist; Learn terms show mastery and 'X/Y correct'.",
      "Learn term detail has a Practice this concept button.",
      "Dashboard gained a Learn progress section.",
    ],
  },
];
